POST http://localhost:7000/api/auth/register

Content-Type: application/json

{ 
    "username": "track",
    "fullname": "Track Prince",
    "email": "trakc@track.com",
    "password" : "tracktrack",
    "passwordConfirmation" : "tracktrack"
}
 
###
POST http://localhost:7000/api/auth/login
Content-Type: application/json

{   
    "username": "prince",
    "email": "gerald@kenneth.com",
    "password" : "ygakenneth"
}

###
GET http://localhost:7000