# POST http://localhost:7000/api/boards
# POST http://localhost:7000/api/auth/login
# Content-Type: application/json

# { 
#     "email": "deimos@mexico.com",
#     "password" : "muygrande"
# }

# { 
#     "name": "akata super broad",
#     "description" : "akata intensely super broad"
# }



POST http://localhost:7000/api/auth/register
# POST http://localhost:7000/api/auth/login
# POST http://localhost:7000/api/auth/logout

Content-Type: application/json

# { 
#     "email": "gerald@kenneth.com",
#     "password" : "ygakenneth"
# }

{ 
    "username": "kenneth",
    "fullname": "Gerald Kenneth",
    "email": "gerald@kenneth.com",
    "password" : "ygakenneth",
    "passwordConfirmation" : "ygakenneth",
    "position" : "admin"
}
